# Generated by Django 3.2 on 2021-05-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.IntegerField(null=True),
        ),
    ]
