# Generated by Django 3.2 on 2021-07-16 06:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoOptionalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'additional_info_optional_items',
            },
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_built_in', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_veranda', models.BooleanField(default=False)),
                ('is_able_deposit_loan', models.BooleanField(default=False)),
                ('is_able_park', models.BooleanField(default=False)),
                ('is_able_pet', models.BooleanField(default=False)),
                ('is_negotiable_mx_cost', models.BooleanField(default=False)),
                ('structure', models.CharField(choices=[('복층', '복층'), ('1.5룸/주방분리형', '1.5룸/주방분리형')], max_length=10, null=True)),
                ('parking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'additional_informations',
            },
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'building_types',
            },
        ),
        migrations.CreateModel(
            name='Dong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
            options={
                'db_table': 'dong',
            },
        ),
        migrations.CreateModel(
            name='Gu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
            options={
                'db_table': 'gu',
            },
        ),
        migrations.CreateModel(
            name='HeatingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'heating_types',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCostOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'maintenance_cost_options',
            },
        ),
        migrations.CreateModel(
            name='MoveInOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('move_in_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'move_in_options',
            },
        ),
        migrations.CreateModel(
            name='OptionalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'optional_items',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_dong', models.CharField(max_length=20, null=True)),
                ('apt_ho', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('regal_address', models.CharField(max_length=500, null=True)),
                ('road_address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.buildingtype')),
                ('dong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.dong')),
                ('gu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.gu')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'room_types',
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sale_types',
            },
        ),
        migrations.CreateModel(
            name='SaleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monthly_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_short', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_info', to='rooms.room')),
                ('sale_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.saletype')),
            ],
            options={
                'db_table': 'sale_informations',
            },
        ),
        migrations.CreateModel(
            name='RoomInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusive_m2', models.DecimalField(decimal_places=5, max_digits=15)),
                ('supply_m2', models.DecimalField(decimal_places=5, max_digits=15)),
                ('building_story', models.IntegerField()),
                ('exclusive_pyeong', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('supply_pyeong', models.IntegerField()),
                ('heating_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.heatingtype')),
                ('move_in_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.moveinoption')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_info', to='rooms.room')),
            ],
            options={
                'db_table': 'room_informations',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomtype'),
        ),
        migrations.CreateModel(
            name='InclusionMaintenanceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.additionalinformation')),
                ('maintenance_cost_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.maintenancecostoption')),
            ],
            options={
                'db_table': 'inclusion_maintenance_cost',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2000)),
                ('sequence', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='dong',
            name='gu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.gu'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('main_text', models.TextField()),
                ('secret_text', models.TextField(null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'db_table': 'descriptions',
            },
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='maintenance_cost_option',
            field=models.ManyToManyField(through='rooms.InclusionMaintenanceCost', to='rooms.MaintenanceCostOption'),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='optional_item',
            field=models.ManyToManyField(through='rooms.AdditionalInfoOptionalItem', to='rooms.OptionalItem'),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='additionalinfooptionalitem',
            name='additional_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.additionalinformation'),
        ),
        migrations.AddField(
            model_name='additionalinfooptionalitem',
            name='optional_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.optionalitem'),
        ),
    ]
