# Generated by Django 3.2 on 2021-04-28 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_agreement', models.BooleanField(default=False)),
                ('parking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'additional_informations',
            },
        ),
        migrations.CreateModel(
            name='AdditionalOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'additional_options',
            },
        ),
        migrations.CreateModel(
            name='AdditionalRoomOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'additional_room_options',
            },
        ),
        migrations.CreateModel(
            name='CheckAdditionalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_able', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'check_additional_options',
            },
        ),
        migrations.CreateModel(
            name='DescriptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('secret_text', models.TextField()),
            ],
            options={
                'db_table': 'description_options',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_address', models.CharField(max_length=500)),
                ('dong', models.CharField(max_length=10)),
                ('ho', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
            options={
                'db_table': 'homes',
            },
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'house_types',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2000)),
                ('sequence', models.IntegerField()),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCostOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'maintenance_cost_options',
            },
        ),
        migrations.CreateModel(
            name='MoveInOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'move_in_options',
            },
        ),
        migrations.CreateModel(
            name='RoomOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'room_options',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'room_types',
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sale_types',
            },
        ),
        migrations.CreateModel(
            name='SaleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monthly_pay', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('is_short', models.BooleanField(default=False)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home')),
                ('sale_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.saletype')),
            ],
            options={
                'db_table': 'sale_informations',
            },
        ),
        migrations.CreateModel(
            name='RoomInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_pyeong', models.IntegerField()),
                ('supply_m2', models.DecimalField(decimal_places=5, max_digits=15)),
                ('exclusive_pyeong', models.IntegerField()),
                ('exclusive_m2', models.DecimalField(decimal_places=5, max_digits=15)),
                ('building_story', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('heating_type', models.CharField(max_length=50)),
                ('move_in_date', models.DateField(null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home')),
                ('move_in_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.moveinoption')),
            ],
            options={
                'db_table': 'room_informatiions',
            },
        ),
        migrations.CreateModel(
            name='InclusionMaintenanceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.additionalinformation')),
                ('maintenance_cost_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.maintenancecostoption')),
            ],
            options={
                'db_table': 'inclusion_maintenance_cost',
            },
        ),
        migrations.AddField(
            model_name='home',
            name='house_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.housetype'),
        ),
        migrations.AddField(
            model_name='home',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.roomtype'),
        ),
    ]
