# Generated by Django 3.2 on 2021-04-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_auto_20210429_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
