# Generated by Django 3.2 on 2021-04-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='legalcode',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
